server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: 47.114.4.104
    port: 7777
    password: zfq17326522631??
    timeout: 300ms # 连接超时时间（毫秒）

mybatis:
  #指定mapper文件位置
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml


